name: svitbo

services:
  frontend:
    build:
      context: ..
      dockerfile: compose.d/Dockerfile.frontend
    container_name: svitbo-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - svitbo_general

networks:
  svitbo_general:
    external: true
