services:
  frontend:
    build:
      context: ..
      dockerfile: compose.d/Dockerfile.frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - composed_svitbo

networks:
  composed_svitbo:
    external: true
